"""initial schema

Revision ID: 14b7965b718d
Revises: 
Create Date: 2025-12-01 14:42:47.453728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14b7965b718d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compartments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenancy_ocid', sa.String(length=255), nullable=False),
    sa.Column('compartment_ocid', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('parent_ocid', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('is_tenancy_root', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['compartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenancy_ocid', 'path', name='uq_compartments_tenancy_path')
    )
    op.create_index(op.f('ix_compartments_compartment_ocid'), 'compartments', ['compartment_ocid'], unique=True)
    op.create_index(op.f('ix_compartments_parent_id'), 'compartments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_compartments_parent_ocid'), 'compartments', ['parent_ocid'], unique=False)
    op.create_index(op.f('ix_compartments_path'), 'compartments', ['path'], unique=False)
    op.create_index(op.f('ix_compartments_tenancy_ocid'), 'compartments', ['tenancy_ocid'], unique=False)
    op.create_table('instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_ocid', sa.String(length=255), nullable=False),
    sa.Column('compartment_ocid', sa.String(length=255), nullable=False),
    sa.Column('compartment_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('availability_domain', sa.String(length=128), nullable=True),
    sa.Column('fault_domain', sa.String(length=64), nullable=True),
    sa.Column('shape', sa.String(length=128), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=64), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('private_ip', sa.String(length=64), nullable=True),
    sa.Column('public_ip', sa.String(length=64), nullable=True),
    sa.Column('freeform_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('defined_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_ocid', sa.String(length=255), nullable=True),
    sa.Column('compartment_path_cache', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compartment_id'], ['compartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instances_compartment_id'), 'instances', ['compartment_id'], unique=False)
    op.create_index(op.f('ix_instances_compartment_ocid'), 'instances', ['compartment_ocid'], unique=False)
    op.create_index(op.f('ix_instances_display_name'), 'instances', ['display_name'], unique=False)
    op.create_index(op.f('ix_instances_instance_ocid'), 'instances', ['instance_ocid'], unique=True)
    op.create_index(op.f('ix_instances_lifecycle_state'), 'instances', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_instances_region'), 'instances', ['region'], unique=False)
    op.create_table('instance_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('managed', sa.Boolean(), nullable=False),
    sa.Column('default_start_cron', sa.String(length=64), nullable=True),
    sa.Column('default_stop_cron', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('protection_flag', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instance_configs_instance_id'), 'instance_configs', ['instance_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instance_configs_instance_id'), table_name='instance_configs')
    op.drop_table('instance_configs')
    op.drop_index(op.f('ix_instances_region'), table_name='instances')
    op.drop_index(op.f('ix_instances_lifecycle_state'), table_name='instances')
    op.drop_index(op.f('ix_instances_instance_ocid'), table_name='instances')
    op.drop_index(op.f('ix_instances_display_name'), table_name='instances')
    op.drop_index(op.f('ix_instances_compartment_ocid'), table_name='instances')
    op.drop_index(op.f('ix_instances_compartment_id'), table_name='instances')
    op.drop_table('instances')
    op.drop_index(op.f('ix_compartments_tenancy_ocid'), table_name='compartments')
    op.drop_index(op.f('ix_compartments_path'), table_name='compartments')
    op.drop_index(op.f('ix_compartments_parent_ocid'), table_name='compartments')
    op.drop_index(op.f('ix_compartments_parent_id'), table_name='compartments')
    op.drop_index(op.f('ix_compartments_compartment_ocid'), table_name='compartments')
    op.drop_table('compartments')
    # ### end Alembic commands ###
